language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - gfortran

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export FC=/usr/local/bin/gfortran-9                              ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export FC=/usr/bin/gfortran                                      ;fi

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_Fortran_COMPILER=$FC

script:
  - cmake --build . --target install
